import { V22_ABILITIES } from "./expansionV22.js";

export const ABILITIES = {
  auto_attack: {
    id: "auto_attack",
    name: "Auto Attack",
    key: "1",
    cooldownMs: 520,
    damageScale: 1,
    range: 3.2,
    description: "Repeated melee swings against the selected target."
  },
  slash: {
    id: "slash",
    name: "Slash",
    key: "2",
    cooldownMs: 4000,
    damageScale: 1.5,
    range: 3.2,
    description: "A committed sword strike for 150% weapon damage."
  },
  hero_pulse: {
    id: "hero_pulse",
    name: "Hero Pulse",
    key: "3",
    trainerId: "mage",
    scalingStat: "magic",
    targetType: "area_hostile",
    price: 100,
    levelRequirement: 2,
    attributeRequirements: {},
    cooldownMs: 12000,
    manaCost: 25,
    radius: 5.2,
    damageScale: 0.8,
    knockback: 3.5,
    description: "A circular shockwave that damages nearby enemies."
  },
  ground_pound: {
    id: "ground_pound",
    name: "Ground Pound",
    trainerId: "mage",
    scalingStat: "strength",
    targetType: "area_hostile",
    price: 150,
    levelRequirement: 3,
    attributeRequirements: { strength: 5 },
    cooldownMs: 10000,
    manaCost: 0,
    radius: 4.8,
    damageScale: 1.15,
    knockback: 5,
    description: "A physical ground shockwave that knocks nearby enemies back."
  },
  fireball: {
    id: "fireball",
    name: "Fireball",
    trainerId: "mage",
    scalingStat: "magic",
    targetType: "hostile",
    price: 200,
    levelRequirement: 4,
    attributeRequirements: { magic: 5 },
    cooldownMs: 6000,
    manaCost: 20,
    range: 18,
    damageScale: 1.1,
    description: "A ranged magical projectile that burns a hostile target."
  },
  dark_punch: {
    id: "dark_punch",
    name: "Dark Punch",
    trainerId: "mage",
    scalingStat: "strength",
    targetType: "hostile",
    price: 250,
    levelRequirement: 5,
    attributeRequirements: { strength: 8 },
    cooldownMs: 7000,
    manaCost: 0,
    range: 3,
    damageScale: 1.35,
    description: "A short-range physical strike with a dark impact."
  },
  water_blast: {
    id: "water_blast",
    name: "Water Blast",
    trainerId: "mage",
    scalingStat: "magic",
    targetType: "hostile",
    price: 300,
    levelRequirement: 5,
    attributeRequirements: { magic: 8 },
    cooldownMs: 8000,
    manaCost: 25,
    range: 16,
    damageScale: 1,
    slowMultiplier: 0.55,
    slowDurationMs: 3500,
    knockback: 1.2,
    description: "A water spell that damages and slows a hostile target."
  },
  healing_orb: {
    id: "healing_orb",
    name: "Healing Orb",
    trainerId: "healer",
    scalingStat: "magic",
    targetType: "self_or_friendly",
    price: 200,
    levelRequirement: 4,
    attributeRequirements: { magic: 5 },
    cooldownMs: 12000,
    manaCost: 25,
    durationMs: 10000,
    pickupRadius: 3.2,
    description: "Creates a healing orb that damaged friendly players can consume."
  },
  mend_ally: {
    id: "mend_ally",
    name: "Mend Ally",
    trainerId: "healer",
    scalingStat: "magic",
    targetType: "friendly",
    price: 350,
    levelRequirement: 6,
    attributeRequirements: { magic: 10 },
    cooldownMs: 8000,
    manaCost: 30,
    range: 15,
    description: "Restores health to a friendly target or yourself."
  },
  whirlwind_cleave: {
    id: "whirlwind_cleave",
    name: "Whirlwind Cleave",
    trainerId: "skill_tree",
    scalingStat: "strength",
    targetType: "area_hostile",
    levelRequirement: 15,
    cooldownMs: 12000,
    manaCost: 0,
    radius: 5.4,
    damageScale: 1.05,
    knockback: 3.2,
    description: "A circular sword attack learned from the Might tier-two tree."
  },
  chain_frost: {
    id: "chain_frost",
    name: "Chain Frost",
    trainerId: "skill_tree",
    scalingStat: "magic",
    targetType: "hostile_chain",
    levelRequirement: 15,
    cooldownMs: 11000,
    manaCost: 32,
    range: 17,
    jumpRange: 7,
    maxTargets: 4,
    damageScale: 0.86,
    description: "A cold spell that jumps between nearby unique enemies."
  },
  radiant_ward: {
    id: "radiant_ward",
    name: "Radiant Ward",
    trainerId: "skill_tree",
    scalingStat: "magic",
    targetType: "friendly_area",
    levelRequirement: 15,
    cooldownMs: 16000,
    manaCost: 35,
    radius: 6,
    durationMs: 4500,
    damageReduction: 0.22,
    description: "A friendly shield pulse learned from the Restoration tier-two tree."
  },
  guard: {
    id: "guard",
    name: "Guard",
    key: "4",
    cooldownMs: 10000,
    durationMs: 3000,
    damageReduction: 0.5,
    description: "Raise your guard, reducing incoming damage by 50% for 3 seconds."
  },
  potion: {
    id: "potion",
    name: "Potion",
    key: "5",
    cooldownMs: 8000,
    heal: 30,
    description: "Drink a small health potion to restore 30 health."
  },
  dash: {
    id: "dash",
    name: "Dash",
    key: "6",
    cooldownMs: 5000,
    distance: 7,
    description: "Burst forward with a short movement trail."
  },
  ...V22_ABILITIES
};
